In [3]:
import theano.tensor as tt
import numpy as np

In [4]:
val = np.random.rand(48,4)
t_val = tt._shared(val)

In [37]:
c = np.random.rand(48)
t_c = tt._shared(c)
theta = tt.pow(3, t_c).dimshuffle(0, 'x')
tt.shape(theta).eval()

array([48,  1])

In [6]:
tt.shape(t_val).eval()

array([48,  4])

In [26]:
theta.eval()

array([[2.21432859, 1.44213097, 2.61260229, 1.55446876, 2.11479266,
        1.81563758, 1.71887939, 1.52450789, 1.4367914 , 2.48000029,
        1.0351509 , 2.6873363 , 1.40016418, 1.17108869, 2.52737469,
        1.1033191 , 1.71912337, 2.32206435, 1.73583573, 1.02699754,
        1.35917364, 2.76991653, 1.93626992, 2.51158559, 2.83274979,
        1.51497779, 1.66228107, 1.0385363 , 2.27057261, 1.03197639,
        2.31712411, 1.68522643, 1.09290524, 1.60585956, 2.38482423,
        2.43899476, 1.15095942, 2.77666977, 1.53540429, 1.63229363,
        2.44818248, 2.11247522, 2.31286898, 2.15832713, 1.86672762,
        1.21935562, 1.97178604, 1.3099863 ]])

In [177]:
pers = tt._shared(np.arange(48*4).reshape(48,4))
pers.eval()

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 40,  41,  42,  43],
       [ 44,  45,  46,  47],
       [ 48,  49,  50,  51],
       [ 52,  53,  54,  55],
       [ 56,  57,  58,  59],
       [ 60,  61,  62,  63],
       [ 64,  65,  66,  67],
       [ 68,  69,  70,  71],
       [ 72,  73,  74,  75],
       [ 76,  77,  78,  79],
       [ 80,  81,  82,  83],
       [ 84,  85,  86,  87],
       [ 88,  89,  90,  91],
       [ 92,  93,  94,  95],
       [ 96,  97,  98,  99],
       [100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119],
       [120, 121, 122, 123],
       [124, 125, 126, 127],
       [128, 129, 130, 131],
       [132, 133, 134, 135],
       [136, 1

In [158]:
choice = tt._shared(np.random.randint(low=0, high=4, size=48))
tt.shape(choice).eval()
choice.eval()

array([1, 2, 2, 3, 0, 2, 1, 0, 1, 3, 3, 1, 3, 1, 1, 0, 2, 0, 1, 1, 2, 1,
       0, 2, 0, 2, 2, 2, 0, 1, 1, 2, 0, 1, 1, 0, 1, 2, 2, 3, 1, 0, 0, 1,
       3, 3, 3, 2])

In [160]:
pers[tt.arange(choice.shape[0]), choice].eval()

array([  1,   6,  10,  15,  16,  22,  25,  28,  33,  39,  43,  45,  51,
        53,  57,  60,  66,  68,  73,  77,  82,  85,  88,  94,  96, 102,
       106, 110, 112, 117, 121, 126, 128, 133, 137, 140, 145, 150, 154,
       159, 161, 164, 168, 173, 179, 183, 187, 190])

In [173]:
pos = tt._shared(np.ones(48))
neg = np.full(48, -1)
neg = tt._shared(neg)

In [106]:
outcome = tt._shared(np.random.randint(low=-1, high=1, size=(48,10)))
outcome.eval()

array([[-1, -1,  0, -1,  0,  0,  0, -1,  0, -1],
       [-1, -1,  0, -1, -1, -1, -1, -1,  0,  0],
       [-1,  0, -1,  0,  0, -1,  0,  0,  0,  0],
       [-1, -1, -1,  0, -1, -1, -1,  0, -1, -1],
       [ 0,  0, -1, -1, -1,  0, -1, -1,  0, -1],
       [ 0,  0,  0,  0,  0,  0, -1,  0, -1,  0],
       [ 0,  0,  0, -1,  0, -1,  0,  0,  0, -1],
       [ 0,  0,  0,  0, -1,  0, -1, -1,  0, -1],
       [-1, -1, -1,  0,  0, -1, -1,  0, -1, -1],
       [ 0,  0, -1,  0, -1, -1, -1, -1,  0, -1],
       [-1,  0, -1, -1,  0,  0,  0, -1,  0,  0],
       [-1,  0, -1,  0, -1,  0, -1,  0, -1, -1],
       [ 0, -1, -1,  0,  0,  0, -1,  0, -1,  0],
       [-1,  0,  0,  0, -1, -1, -1, -1, -1,  0],
       [-1,  0, -1, -1,  0, -1,  0,  0, -1,  0],
       [ 0, -1,  0, -1, -1, -1,  0, -1, -1, -1],
       [-1,  0, -1,  0,  0,  0,  0, -1, -1, -1],
       [ 0, -1,  0,  0,  0,  0, -1, -1, -1, -1],
       [-1,  0, -1,  0, -1,  0, -1, -1, -1,  0],
       [ 0, -1,  0, -1, -1,  0,  0, -1, -1, -1],
       [ 0,  0,  0, 

In [180]:
update_pers = tt.switch(outcome[:, 1] >= 0, pos, neg)
update_pers.eval()

array([-1., -1.,  1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1., -1.,
        1.,  1., -1.,  1., -1.,  1., -1.,  1., -1., -1., -1.,  1.,  1.,
       -1., -1., -1.,  1.,  1., -1.,  1.,  1., -1., -1., -1.,  1., -1.,
        1.,  1., -1.,  1.,  1.,  1., -1.,  1., -1.])

In [181]:
pers = tt.inc_subtensor(pers[tt.arange(choice.shape[0]), choice], update_pers)

In [182]:
pers.eval()

array([[  0,  -1,   2,   3],
       [  4,   5,   4,   7],
       [  8,   9,  12,  11],
       [ 12,  13,  14,  13],
       [ 18,  17,  18,  19],
       [ 20,  21,  24,  23],
       [ 24,  27,  26,  27],
       [ 30,  29,  30,  31],
       [ 32,  31,  34,  35],
       [ 36,  37,  38,  41],
       [ 40,  41,  42,  45],
       [ 44,  47,  46,  47],
       [ 48,  49,  50,  49],
       [ 52,  55,  54,  55],
       [ 56,  59,  58,  59],
       [ 58,  61,  62,  63],
       [ 64,  65,  68,  67],
       [ 66,  69,  70,  71],
       [ 72,  75,  74,  75],
       [ 76,  75,  78,  79],
       [ 80,  81,  84,  83],
       [ 84,  83,  86,  87],
       [ 86,  89,  90,  91],
       [ 92,  93,  92,  95],
       [ 98,  97,  98,  99],
       [100, 101, 104, 103],
       [104, 105, 104, 107],
       [108, 109, 108, 111],
       [110, 113, 114, 115],
       [116, 119, 118, 119],
       [120, 123, 122, 123],
       [124, 125, 124, 127],
       [130, 129, 130, 131],
       [132, 135, 134, 135],
       [136, 1

In [170]:
tt.shape(outcome[:, 1]).eval()

array([48])

In [193]:
phi = tt._shared(np.arange(48).reshape(48,))
ev = tt._shared(np.arange(48*4).reshape(48,4))

In [185]:
util = tt._shared(np.arange(48))

In [196]:
inc = phi * (util - ev[tt.arange(choice.shape[0]), choice])
inc.eval()

array([    0,    -5,   -16,   -36,   -48,   -85,  -114,  -147,  -200,
        -270,  -330,  -374,  -468,  -520,  -602,  -675,  -800,  -867,
        -990, -1102, -1240, -1344, -1452, -1633, -1728, -1925, -2080,
       -2241, -2352, -2552, -2730, -2945, -3072, -3300, -3502, -3675,
       -3924, -4181, -4408, -4680, -4840, -5043, -5292, -5590, -5940,
       -6210, -6486, -6721])

In [197]:
ev = tt.inc_subtensor(ev[tt.arange(choice.shape[0]), choice], inc)

In [198]:
ev.eval()

array([[    0,     1,     2,     3],
       [    4,     5,     1,     7],
       [    8,     9,    -6,    11],
       [   12,    13,    14,   -21],
       [  -32,    17,    18,    19],
       [   20,    21,   -63,    23],
       [   24,   -89,    26,    27],
       [ -119,    29,    30,    31],
       [   32,  -167,    34,    35],
       [   36,    37,    38,  -231],
       [   40,    41,    42,  -287],
       [   44,  -329,    46,    47],
       [   48,    49,    50,  -417],
       [   52,  -467,    54,    55],
       [   56,  -545,    58,    59],
       [ -615,    61,    62,    63],
       [   64,    65,  -734,    67],
       [ -799,    69,    70,    71],
       [   72,  -917,    74,    75],
       [   76, -1025,    78,    79],
       [   80,    81, -1158,    83],
       [   84, -1259,    86,    87],
       [-1364,    89,    90,    91],
       [   92,    93, -1539,    95],
       [-1632,    97,    98,    99],
       [  100,   101, -1823,   103],
       [  104,   105, -1974,   107],
 